url: "https://boris-isma-4240.github.io"
baseurl: "/lab"  # comment

title: LAB
description: lab
theme: null

collections:
  courses:
    output: true     
    permalink: /courses/:name/

  projects:
    output: true     
    permalink: /projects/:name/

  news:
    output: true     
    permalink: /news/:name/
